apiVersion: v1
kind: Pod
metadata:
    name: frontend-pod
    labels:
      name: frontend-pod
      env: aurtask
spec:
   containers:
    - name: frontend
      image: crazyfordevops/frontend:vFinal
      ports:
        - containerPort: 8081
      env:
        - name: IP
          value: "backend"
