apiVersion: v1
kind: Pod
metadata:
    name: frontend-pod
    labels:
      name: frontend-pod
      env: aurtask
spec:
   containers:
    - name: frontend
      image: crazyfordevops/frontend
      ports:
        - containerPort: 80
